USE db24;

/*DELIMITER $$
CREATE TRIGGER MyTBL_0a_guard1 BEFORE INSERT ON MyTBL_0a
FOR EACH ROW
BEGIN
DECLARE a varchar(100);
SELECT CURRENT_USER() INTO @a;
SIGNAL SQLSTATE '50000' SET message_text=@a;
END;$$
DELIMITER ;

INSERT INTO MyTBL_0a (Title) VALUE ('AAA');*/

CREATE TABLE `MyTBL_0c` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `Title` varchar(20) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
